from datetime import timedelta
from decimal import Decimal

from django.core.management.base import BaseCommand
from django.utils import timezone

from shop.models import Category, Deal, Product, Review


CATEGORIES = [
    ('prebuilt', 'Prebuilt Desktops'),
    ('gpu', 'Graphics Cards'),
    ('cpu', 'Processors'),
    ('ram', 'System RAM'),
    ('storage', 'Storage'),
    ('motherboard', 'Motherboards'),
    ('psu', 'Power Supplies'),
    ('cooling', 'Cooling'),
    ('case', 'Cases'),
]

PRODUCTS = [
    {
        'name': 'Overclock Phantom X1',
        'slug': 'overclock-phantom-x1',
        'category': 'prebuilt',
        'description': 'Flagship 4K gaming rig with custom liquid cooling loop and tempered glass chassis.',
        'price': Decimal('3299.99'),
        'old_price': Decimal('3799.99'),
        'badge': 'FLAGSHIP',
        'stock': 12,
        'cpu': 'Intel Core i9-14900K',
        'gpu': 'NVIDIA RTX 4090 24GB',
        'ram': '64GB DDR5-6000 RGB',
        'storage': '2TB NVMe Gen5 SSD',
        'mobo': 'ASUS ROG Maximus Z790',
        'psu': '1000W 80+ Platinum',
        'cooler': 'Custom 360mm AIO Loop',
        'case': 'Lian Li O11 Dynamic EVO',
        'rating': Decimal('4.9'),
        'reviews_count': 47,
        'is_featured': True,
        'is_trending': True,
    },
    {
        'name': 'Overclock Vortex Pro',
        'slug': 'overclock-vortex-pro',
        'category': 'prebuilt',
        'description': 'High-refresh 1440p esports machine tuned for competitive gaming.',
        'price': Decimal('2199.99'),
        'old_price': None,
        'badge': 'POPULAR',
        'stock': 18,
        'cpu': 'AMD Ryzen 7 7800X3D',
        'gpu': 'NVIDIA RTX 4070 Ti Super',
        'ram': '32GB DDR5-5600',
        'storage': '1TB NVMe Gen4 SSD',
        'mobo': 'MSI MAG B650 Tomahawk',
        'psu': '850W 80+ Gold',
        'cooler': '240mm AIO Liquid Cooler',
        'case': 'NZXT H7 Flow',
        'rating': Decimal('4.8'),
        'reviews_count': 63,
        'is_featured': True,
        'is_trending': True,
    },
    {
        'name': 'Overclock Neon Strike',
        'slug': 'overclock-neon-strike',
        'category': 'prebuilt',
        'description': 'RGB-forward mid-range build for streamers and content creators.',
        'price': Decimal('1599.99'),
        'old_price': Decimal('1799.99'),
        'badge': 'NEW',
        'stock': 25,
        'cpu': 'AMD Ryzen 5 7600X',
        'gpu': 'NVIDIA RTX 4060 Ti 16GB',
        'ram': '32GB DDR5-5200 RGB',
        'storage': '1TB NVMe Gen4 SSD',
        'mobo': 'Gigabyte B650 AORUS Elite',
        'psu': '750W 80+ Gold',
        'cooler': 'Tower Air Cooler RGB',
        'case': 'Corsair 4000D Airflow',
        'rating': Decimal('4.6'),
        'reviews_count': 31,
        'is_featured': True,
        'is_trending': False,
    },
    {
        'name': 'Overclock Entry Node',
        'slug': 'overclock-entry-node',
        'category': 'prebuilt',
        'description': 'Affordable 1080p gaming desktop for first-time builders and casual gamers.',
        'price': Decimal('899.99'),
        'old_price': Decimal('999.99'),
        'badge': '',
        'stock': 30,
        'cpu': 'Intel Core i5-13400F',
        'gpu': 'NVIDIA RTX 4060 8GB',
        'ram': '16GB DDR5-4800',
        'storage': '512GB NVMe SSD',
        'mobo': 'ASRock B760M Pro RS',
        'psu': '650W 80+ Bronze',
        'cooler': 'Stock Air Cooler',
        'case': 'Fractal Focus G',
        'rating': Decimal('4.4'),
        'reviews_count': 22,
        'is_featured': False,
        'is_trending': True,
    },
    {
        'name': 'NVIDIA GeForce RTX 4090 Founders Edition',
        'slug': 'nvidia-rtx-4090-fe',
        'category': 'gpu',
        'description': 'The ultimate GPU for 4K ray-traced gaming and AI workloads.',
        'price': Decimal('1599.99'),
        'old_price': Decimal('1799.99'),
        'badge': 'FLAGSHIP',
        'stock': 8,
        'cpu': '',
        'gpu': '24GB GDDR6X | 16384 CUDA Cores',
        'ram': '',
        'storage': '',
        'mobo': '',
        'psu': 'Requires 850W+ PSU',
        'cooler': 'Triple-fan vapor chamber',
        'case': '',
        'rating': Decimal('4.9'),
        'reviews_count': 89,
        'is_featured': True,
        'is_trending': True,
    },
    {
        'name': 'NVIDIA GeForce RTX 4070 Super',
        'slug': 'nvidia-rtx-4070-super',
        'category': 'gpu',
        'description': 'Excellent 1440p performance with DLSS 3 frame generation.',
        'price': Decimal('599.99'),
        'old_price': Decimal('649.99'),
        'badge': 'POPULAR',
        'stock': 22,
        'cpu': '',
        'gpu': '12GB GDDR6X | 7168 CUDA Cores',
        'ram': '',
        'storage': '',
        'mobo': '',
        'psu': 'Requires 650W+ PSU',
        'cooler': 'Dual-fan axial',
        'case': '',
        'rating': Decimal('4.7'),
        'reviews_count': 54,
        'is_featured': False,
        'is_trending': True,
    },
    {
        'name': 'AMD Radeon RX 7900 XTX',
        'slug': 'amd-rx-7900-xtx',
        'category': 'gpu',
        'description': 'AMD flagship with 24GB VRAM for high-res gaming and creative work.',
        'price': Decimal('949.99'),
        'old_price': Decimal('1049.99'),
        'badge': '',
        'stock': 14,
        'cpu': '',
        'gpu': '24GB GDDR6 | RDNA 3 Architecture',
        'ram': '',
        'storage': '',
        'mobo': '',
        'psu': 'Requires 800W+ PSU',
        'cooler': 'Triple-fan reference',
        'case': '',
        'rating': Decimal('4.6'),
        'reviews_count': 38,
        'is_featured': False,
        'is_trending': False,
    },
    {
        'name': 'Intel Core i9-14900K',
        'slug': 'intel-i9-14900k',
        'category': 'cpu',
        'description': '24-core hybrid processor for maximum gaming and productivity performance.',
        'price': Decimal('549.99'),
        'old_price': Decimal('599.99'),
        'badge': 'FLAGSHIP',
        'stock': 20,
        'cpu': '24 Cores (8P+16E) | 6.0GHz Boost | LGA1700',
        'gpu': '',
        'ram': 'DDR5-5600 / DDR4-3200',
        'storage': '',
        'mobo': 'LGA1700 Socket',
        'psu': '',
        'cooler': 'Requires robust cooling',
        'case': '',
        'rating': Decimal('4.8'),
        'reviews_count': 41,
        'is_featured': True,
        'is_trending': False,
    },
    {
        'name': 'AMD Ryzen 7 7800X3D',
        'slug': 'amd-ryzen-7-7800x3d',
        'category': 'cpu',
        'description': 'The best gaming CPU with 3D V-Cache technology for unmatched frame rates.',
        'price': Decimal('399.99'),
        'old_price': None,
        'badge': 'POPULAR',
        'stock': 35,
        'cpu': '8 Cores | 5.0GHz Boost | AM5 Socket',
        'gpu': '',
        'ram': 'DDR5-5200',
        'storage': '',
        'mobo': 'AM5 Socket',
        'psu': '',
        'cooler': '65W TDP — stock cooler OK',
        'case': '',
        'rating': Decimal('4.9'),
        'reviews_count': 112,
        'is_featured': True,
        'is_trending': True,
    },
    {
        'name': 'Corsair Vengeance RGB 32GB DDR5-6000',
        'slug': 'corsair-vengeance-rgb-32gb-ddr5',
        'category': 'ram',
        'description': 'Low-latency DDR5 kit with dynamic RGB lighting and aluminum heat spreaders.',
        'price': Decimal('129.99'),
        'old_price': Decimal('159.99'),
        'badge': '',
        'stock': 50,
        'cpu': '',
        'gpu': '',
        'ram': '32GB (2x16GB) DDR5-6000 CL30',
        'storage': '',
        'mobo': 'Intel XMP 3.0 / AMD EXPO',
        'psu': '',
        'cooler': '',
        'case': '',
        'rating': Decimal('4.7'),
        'reviews_count': 28,
        'is_featured': False,
        'is_trending': True,
    },
    {
        'name': 'G.Skill Trident Z5 Neo 64GB DDR5-6000',
        'slug': 'gskill-trident-z5-neo-64gb',
        'category': 'ram',
        'description': 'Premium 64GB kit optimized for AMD AM5 platforms.',
        'price': Decimal('229.99'),
        'old_price': Decimal('269.99'),
        'badge': 'NEW',
        'stock': 18,
        'cpu': '',
        'gpu': '',
        'ram': '64GB (2x32GB) DDR5-6000 CL32',
        'storage': '',
        'mobo': 'AMD EXPO Certified',
        'psu': '',
        'cooler': '',
        'case': '',
        'rating': Decimal('4.8'),
        'reviews_count': 15,
        'is_featured': False,
        'is_trending': False,
    },
    {
        'name': 'Samsung 990 Pro 2TB NVMe SSD',
        'slug': 'samsung-990-pro-2tb',
        'category': 'storage',
        'description': 'Blazing Gen4 NVMe drive with 7,450 MB/s read speeds.',
        'price': Decimal('179.99'),
        'old_price': Decimal('219.99'),
        'badge': 'POPULAR',
        'stock': 40,
        'cpu': '',
        'gpu': '',
        'ram': '',
        'storage': '2TB NVMe Gen4 | 7450/6900 MB/s',
        'mobo': 'M.2 2280 PCIe 4.0',
        'psu': '',
        'cooler': '',
        'case': '',
        'rating': Decimal('4.8'),
        'reviews_count': 76,
        'is_featured': True,
        'is_trending': False,
    },
    {
        'name': 'WD Black SN850X 4TB NVMe SSD',
        'slug': 'wd-black-sn850x-4tb',
        'category': 'storage',
        'description': 'Massive 4TB storage for game libraries and creative projects.',
        'price': Decimal('349.99'),
        'old_price': Decimal('399.99'),
        'badge': '',
        'stock': 15,
        'cpu': '',
        'gpu': '',
        'ram': '',
        'storage': '4TB NVMe Gen4 | 7300/6600 MB/s',
        'mobo': 'M.2 2280 PCIe 4.0',
        'psu': '',
        'cooler': '',
        'case': '',
        'rating': Decimal('4.7'),
        'reviews_count': 33,
        'is_featured': False,
        'is_trending': False,
    },
    {
        'name': 'ASUS ROG Strix Z790-E Gaming WiFi',
        'slug': 'asus-rog-strix-z790-e',
        'category': 'motherboard',
        'description': 'Premium Intel Z790 board with PCIe 5.0, WiFi 6E, and robust VRM.',
        'price': Decimal('449.99'),
        'old_price': None,
        'badge': 'FLAGSHIP',
        'stock': 12,
        'cpu': 'Intel LGA1700 | Z790 Chipset',
        'gpu': 'PCIe 5.0 x16',
        'ram': '4x DDR5 slots up to 7800+ MT/s',
        'storage': '4x M.2 slots',
        'mobo': 'ATX | WiFi 6E | 2.5Gb LAN',
        'psu': '',
        'cooler': '',
        'case': '',
        'rating': Decimal('4.7'),
        'reviews_count': 19,
        'is_featured': False,
        'is_trending': False,
    },
    {
        'name': 'MSI MAG B650 Tomahawk WiFi',
        'slug': 'msi-mag-b650-tomahawk',
        'category': 'motherboard',
        'description': 'Reliable AM5 motherboard with excellent value and solid build quality.',
        'price': Decimal('219.99'),
        'old_price': Decimal('249.99'),
        'badge': 'POPULAR',
        'stock': 28,
        'cpu': 'AMD AM5 | B650 Chipset',
        'gpu': 'PCIe 4.0 x16',
        'ram': '4x DDR5 slots up to 6400 MT/s',
        'storage': '2x M.2 slots',
        'mobo': 'ATX | WiFi 6E | 2.5Gb LAN',
        'psu': '',
        'cooler': '',
        'case': '',
        'rating': Decimal('4.6'),
        'reviews_count': 44,
        'is_featured': False,
        'is_trending': True,
    },
    {
        'name': 'Corsair RM1000x Shift 1000W',
        'slug': 'corsair-rm1000x-shift',
        'category': 'psu',
        'description': 'Modular 1000W PSU with side-connect design for cleaner cable management.',
        'price': Decimal('219.99'),
        'old_price': Decimal('249.99'),
        'badge': '',
        'stock': 20,
        'cpu': '',
        'gpu': '',
        'ram': '',
        'storage': '',
        'mobo': '',
        'psu': '1000W | 80+ Gold | Fully Modular',
        'cooler': 'Zero RPM fan mode',
        'case': 'ATX Form Factor',
        'rating': Decimal('4.8'),
        'reviews_count': 27,
        'is_featured': False,
        'is_trending': False,
    },
    {
        'name': 'NZXT Kraken Elite 360 RGB',
        'slug': 'nzxt-kraken-elite-360',
        'category': 'cooling',
        'description': 'Premium 360mm AIO with LCD display and customizable RGB lighting.',
        'price': Decimal('279.99'),
        'old_price': Decimal('319.99'),
        'badge': 'NEW',
        'stock': 16,
        'cpu': 'Intel LGA1700 / AMD AM5',
        'gpu': '',
        'ram': '',
        'storage': '',
        'mobo': '',
        'psu': '',
        'cooler': '360mm AIO | LCD Display | RGB',
        'case': '',
        'rating': Decimal('4.7'),
        'reviews_count': 21,
        'is_featured': True,
        'is_trending': False,
    },
    {
        'name': 'Noctua NH-D15 chromax.black',
        'slug': 'noctua-nh-d15-chromax',
        'category': 'cooling',
        'description': 'Legendary dual-tower air cooler for silent high-performance cooling.',
        'price': Decimal('109.99'),
        'old_price': None,
        'badge': 'POPULAR',
        'stock': 32,
        'cpu': 'Universal Intel/AMD',
        'gpu': '',
        'ram': '',
        'storage': '',
        'mobo': '',
        'psu': '',
        'cooler': 'Dual-tower | 2x NF-A15 PWM fans',
        'case': '',
        'rating': Decimal('4.9'),
        'reviews_count': 98,
        'is_featured': False,
        'is_trending': True,
    },
    {
        'name': 'Lian Li O11 Dynamic EVO',
        'slug': 'lian-li-o11-dynamic-evo',
        'category': 'case',
        'description': 'Iconic dual-chamber case with panoramic glass and modular interior.',
        'price': Decimal('169.99'),
        'old_price': Decimal('189.99'),
        'badge': 'FLAGSHIP',
        'stock': 24,
        'cpu': '',
        'gpu': 'GPU clearance up to 420mm',
        'ram': '',
        'storage': '',
        'mobo': 'E-ATX / ATX / mATX / ITX',
        'psu': 'PSU shroud included',
        'cooler': '360mm radiator support top/side',
        'case': 'Mid-Tower | Tempered Glass',
        'rating': Decimal('4.8'),
        'reviews_count': 67,
        'is_featured': True,
        'is_trending': True,
    },
    {
        'name': 'Fractal Design North',
        'slug': 'fractal-design-north',
        'category': 'case',
        'description': 'Scandinavian-inspired mid-tower with wood front panel and whisper-quiet airflow.',
        'price': Decimal('139.99'),
        'old_price': None,
        'badge': '',
        'stock': 19,
        'cpu': '',
        'gpu': 'GPU clearance up to 355mm',
        'ram': '',
        'storage': '',
        'mobo': 'ATX / mATX / ITX',
        'psu': 'PSU shroud included',
        'cooler': '280mm radiator support front',
        'case': 'Mid-Tower | Mesh/Wood Front',
        'rating': Decimal('4.7'),
        'reviews_count': 35,
        'is_featured': False,
        'is_trending': False,
    },
]

# PC Builder metadata keyed by product slug
BUILDER_PARTS = {
    'intel-i9-14900k': {'component_type': 'cpu', 'wattage': 125, 'socket': 'LGA1700', 'is_builder_part': True},
    'amd-ryzen-7-7800x3d': {'component_type': 'cpu', 'wattage': 120, 'socket': 'AM5', 'is_builder_part': True},
    'asus-rog-strix-z790-e': {'component_type': 'mobo', 'wattage': 15, 'socket': 'LGA1700', 'is_builder_part': True},
    'msi-mag-b650-tomahawk': {'component_type': 'mobo', 'wattage': 15, 'socket': 'AM5', 'is_builder_part': True},
    'nvidia-rtx-4090-fe': {'component_type': 'gpu', 'wattage': 450, 'socket': '', 'is_builder_part': True},
    'nvidia-rtx-4070-super': {'component_type': 'gpu', 'wattage': 220, 'socket': '', 'is_builder_part': True},
    'amd-rx-7900-xtx': {'component_type': 'gpu', 'wattage': 355, 'socket': '', 'is_builder_part': True},
    'corsair-vengeance-rgb-32gb-ddr5': {'component_type': 'ram', 'wattage': 10, 'socket': '', 'is_builder_part': True},
    'gskill-trident-z5-neo-64gb': {'component_type': 'ram', 'wattage': 12, 'socket': '', 'is_builder_part': True},
    'samsung-990-pro-2tb': {'component_type': 'storage', 'wattage': 8, 'socket': '', 'is_builder_part': True},
    'wd-black-sn850x-4tb': {'component_type': 'storage', 'wattage': 10, 'socket': '', 'is_builder_part': True},
    'corsair-rm1000x-shift': {'component_type': 'psu', 'wattage': 1000, 'socket': '', 'is_builder_part': True},
    'nzxt-kraken-elite-360': {'component_type': 'cooler', 'wattage': 15, 'socket': '', 'is_builder_part': True},
    'noctua-nh-d15-chromax': {'component_type': 'cooler', 'wattage': 5, 'socket': '', 'is_builder_part': True},
    'lian-li-o11-dynamic-evo': {'component_type': 'case', 'wattage': 20, 'socket': '', 'is_builder_part': True},
    'fractal-design-north': {'component_type': 'case', 'wattage': 15, 'socket': '', 'is_builder_part': True},
}

REVIEWS = [
    ('overclock-phantom-x1', 'CyberRig42', 5, 'Absolute beast', 'Runs every game at 4K max settings. The liquid loop keeps temps under 65°C even during marathon sessions.'),
    ('overclock-vortex-pro', 'FPS_Demon', 5, 'Esports king', '7800X3D + 4070 Ti Super combo is unbeatable for competitive shooters. 360+ FPS in Valorant.'),
    ('nvidia-rtx-4090-fe', 'RenderLord', 5, 'Worth every penny', 'Incredible for both gaming and Blender renders. DLSS 3 is magic.'),
    ('amd-ryzen-7-7800x3d', 'CacheKing', 5, 'Best gaming CPU', 'Upgraded from a 5800X3D and the improvement in CPU-bound games is massive.'),
    ('samsung-990-pro-2tb', 'LoadTimeZero', 4, 'Blazing fast', 'Windows boots in 8 seconds. Game loads are nearly instant. Wish it was cheaper.'),
    ('lian-li-o11-dynamic-evo', 'RGB_Master', 5, 'Showcase perfection', 'The glass panels and cable management options make this the ultimate display case.'),
]

DEALS = [
    {
        'title': 'GPU Flash Sale',
        'slug': 'gpu-flash-sale',
        'description': 'Limited-time discounts on flagship and mid-range graphics cards. Upgrade your frame rates before stock runs out.',
        'discount_label': 'Up to 15% OFF',
        'badge': 'FLASH SALE',
        'days': 7,
        'product_slugs': ['nvidia-rtx-4090-fe', 'nvidia-rtx-4070-super', 'amd-rx-7900-xtx'],
    },
    {
        'title': 'Prebuilt Power Hour',
        'slug': 'prebuilt-power-hour',
        'description': 'Save big on our custom-built gaming desktops. Every rig is hand-assembled and stress-tested.',
        'discount_label': 'Up to $500 OFF',
        'badge': 'HOT DEAL',
        'days': 5,
        'product_slugs': ['overclock-phantom-x1', 'overclock-neon-strike', 'overclock-entry-node'],
    },
    {
        'title': 'RAM & Storage Blowout',
        'slug': 'ram-storage-blowout',
        'description': 'Boost your system speed with discounted memory and NVMe drives.',
        'discount_label': 'Up to 20% OFF',
        'badge': 'CLEARANCE',
        'days': 10,
        'product_slugs': ['corsair-vengeance-rgb-32gb-ddr5', 'gskill-trident-z5-neo-64gb', 'samsung-990-pro-2tb', 'wd-black-sn850x-4tb'],
    },
]


class Command(BaseCommand):
    help = 'Seeds categories, products, deals, and sample reviews'

    def add_arguments(self, parser):
        parser.add_argument(
            '--clear',
            action='store_true',
            help='Delete existing catalog data before seeding',
        )

    def handle(self, *args, **options):
        if options['clear']:
            Review.objects.all().delete()
            Deal.objects.all().delete()
            Product.objects.all().delete()
            Category.objects.all().delete()
            self.stdout.write(self.style.WARNING('Cleared existing catalog data.'))

        category_map = {}
        for id_key, name in CATEGORIES:
            cat, _ = Category.objects.get_or_create(id_key=id_key, defaults={'name': name})
            category_map[id_key] = cat

        product_map = {}
        for data in PRODUCTS:
            cat_key = data.pop('category')
            slug = data['slug']
            builder_meta = BUILDER_PARTS.get(slug, {
                'component_type': '', 'wattage': 0, 'socket': '', 'is_builder_part': False,
            })
            product, created = Product.objects.update_or_create(
                slug=slug,
                defaults={
                    **data,
                    **builder_meta,
                    'category': category_map[cat_key],
                    'in_stock': data['stock'] > 0,
                },
            )
            product_map[slug] = product
            action = 'Created' if created else 'Updated'
            self.stdout.write(f'  {action}: {product.name}')

        now = timezone.now()
        for deal_data in DEALS:
            product_slugs = deal_data.pop('product_slugs')
            days = deal_data.pop('days')
            deal, created = Deal.objects.update_or_create(
                slug=deal_data['slug'],
                defaults={
                    **deal_data,
                    'starts_at': now - timedelta(days=1),
                    'ends_at': now + timedelta(days=days),
                    'is_active': True,
                },
            )
            deal.products.set([product_map[s] for s in product_slugs])
            action = 'Created' if created else 'Updated'
            self.stdout.write(f'  {action} deal: {deal.title}')

        for product_slug, author, rating, title, content in REVIEWS:
            product = product_map[product_slug]
            Review.objects.get_or_create(
                product=product,
                author_name=author,
                title=title,
                defaults={
                    'rating': rating,
                    'content': content,
                    'is_approved': True,
                    'source': 'verified',
                },
            )

        builder_count = Product.objects.filter(is_builder_part=True).count()
        self.stdout.write(self.style.SUCCESS(
            f'\nSeeded {len(category_map)} categories, {len(product_map)} products '
            f'({builder_count} builder parts), {len(DEALS)} deals, and {len(REVIEWS)} reviews.'
        ))
