# Generated by Django 6.0.6 on 2026-06-05 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_key', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('resolved', 'Resolved')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.CharField(blank=True, help_text='Static image filename without extension', max_length=200)),
                ('image_upload', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('badge', models.CharField(blank=True, max_length=50)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('in_stock', models.BooleanField(default=True)),
                ('cpu', models.CharField(blank=True, max_length=200)),
                ('gpu', models.CharField(blank=True, max_length=200)),
                ('ram', models.CharField(blank=True, max_length=200)),
                ('storage', models.CharField(blank=True, max_length=200)),
                ('mobo', models.CharField(blank=True, max_length=200)),
                ('psu', models.CharField(blank=True, max_length=200)),
                ('cooler', models.CharField(blank=True, max_length=200)),
                ('case', models.CharField(blank=True, max_length=200)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.category')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('performance', 'Performance'), ('design', 'Design'), ('value', 'Value'), ('support', 'Support'), ('general', 'General')], default='general', max_length=50)),
                ('source', models.CharField(choices=[('website', 'Website'), ('verified', 'Verified Purchase'), ('external', 'External')], default='website', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
